version: "3.7"

services:
  php:
    build: ./docker/php
    tty: true
    container_name: rigor-talks-php
    ports:
      - "9000:9000"
    volumes:
      - .:/home/app

  nginx:
    build: ./docker/nginx
    container_name: rigor-talks-nginx
    tty: true
    depends_on:
      - php
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - .:/home/app
